package br.com.app.horadorango.usecase;

import br.com.app.horadorango.domains.Menu;
import br.com.app.horadorango.domains.Place;
import org.springframework.stereotype.Service;

import java.util.Arrays;
import java.util.List;

@Service
public class PlaceUseCase {

    public List<Place> listAllPlaces() {
        return mockPlaces();
    }

    public Place getMenuPlace(Integer placeId) {
        return mockPlaces().stream().filter(p -> p.getId().compareTo(placeId) == 0).findFirst().get();
    }

    private List<Place> mockPlaces() {
        List<Menu> pizzaMenu = Arrays.asList(Menu.builder()
                .id(1)
                .item("Pizza de Calabresa")
                .price(25.9)
                .build(), Menu.builder()
                .id(2)
                .item("Pizza de Mussarela")
                .price(26.9)
                .build(), Menu.builder()
                .id(3)
                .item("Pizza de Frango com Catupiry")
                .price(28.4)
                .build(), Menu.builder()
                .id(4)
                .item("Pizza de Portuguesa")
                .price(29.7)
                .build(), Menu.builder()
                .id(5)
                .item("Pizza de Marguerita")
                .price(28.4)
                .build(), Menu.builder()
                .id(6)
                .item("Pizza de Palmito")
                .price(29.0)
                .build(), Menu.builder()
                .id(7)
                .item("Pizza de Milho")
                .price(27.8)
                .build());

        List<Menu> menuComidaJaponesa = Arrays.asList(Menu.builder()
                .id(1)
                .item("Rodizio Delivery - Serve 2 pessoas\n2 Rolinhos de Legumes\n2 Rolinhos de Queijo\n2 Salmão\n3 Temakis\n2 Hot holl")
                .price(60.9)
                .build(), Menu.builder()
                .id(2)
                .item("Combo 10 Unidades\n2 Temakis\n4 Sashimi de Salmão\n2 Yakissoba\n2 Rolinhos de Queijo")
                .price(36.9)
                .build(), Menu.builder()
                .id(3)
                .item("Missoshiru")
                .price(7.0)
                .build(), Menu.builder()
                .id(4)
                .item("Rolinho Camarão Cremoso - 1 Unidade")
                .price(7.0)
                .build(), Menu.builder()
                .id(5)
                .item("Rolinho Primavera - 1 Unidade")
                .price(7.0)
                .build(), Menu.builder()
                .id(6)
                .item("Rolinho de Queijo - 1 Unidade")
                .price(7.0)
                .build(), Menu.builder()
                .id(7)
                .item("Coca Cola")
                .price(8.0)
                .build());
        List<Menu> menuSalgados = Arrays.asList(Menu.builder()
                .id(1)
                .item("Coxinha - 100 Unidades")
                .price(22.0)
                .build(), Menu.builder()
                .id(2)
                .item("Risóli de Queijo - 100 Unidades")
                .price(26.0)
                .build(), Menu.builder()
                .id(3)
                .item("Bolinho de Queijo - 100 Unidades")
                .price(23.0)
                .build(), Menu.builder()
                .id(4)
                .item("Risóli de Presunto e Queijo - 100 Unidades")
                .price(26.0)
                .build(), Menu.builder()
                .id(5)
                .item("Empadinha de Palmito")
                .price(28.4)
                .build(), Menu.builder()
                .id(6)
                .item("Risóli de Palmito")
                .price(27.0)
                .build(), Menu.builder()
                .id(7)
                .item("Coca Cola")
                .price(7.0)
                .build());
        List<Menu> menuLanches = Arrays.asList(Menu.builder()
                .id(1)
                .item("X-Salada")
                .price(16.9)
                .build(), Menu.builder()
                .id(2)
                .item("X-Burguer")
                .price(18.0)
                .build(), Menu.builder()
                .id(3)
                .item("X-Picanha")
                .price(20.0)
                .build(), Menu.builder()
                .id(4)
                .item("X-Egg")
                .price(19.5)
                .build(), Menu.builder()
                .id(5)
                .item("X-Calabresa")
                .price(18.0)
                .build(), Menu.builder()
                .id(6)
                .item("X-TUDO")
                .price(29.0)
                .build(), Menu.builder()
                .id(7)
                .item("Coca Cola")
                .price(7.0)
                .build());

        return Arrays.asList(Place.builder()
                .id(1)
                .name("Pizzaria Alvorada")
                .image("http://www.leaodesign.com/images/portfolio/criacao-de-logotipos/5-single.png")
                .kindOfFood("Pizzas")
                .phone("11976895432")
                .address("Rua Calixto Fonseca, 20")
                .menu(pizzaMenu)
                .build(), Place.builder()
                .id(2)
                .name("Sushi Point")
                .image("https://st3.depositphotos.com/1028367/13834/v/1600/depositphotos_138349100-stock-illustration-logo-for-japanese-food-restaurants.jpg")
                .kindOfFood("Comida Japonesa")
                .phone("1123456578")
                .address("Rua João Bodim, 234")
                .menu(menuComidaJaponesa)
                .build(), Place.builder()
                .id(3)
                .name("Sushi Aky")
                .image("http://www.sushiaky.com.br/images/logo.png")
                .kindOfFood("Comida Japonesa")
                .phone("11966825492")
                .address("Rua Bernado Barbosa, 50")
                .menu(menuLanches)
                .build(), Place.builder()
                .id(4)
                .name("Cheiger Lanches")
                .image("https://s3-sa-east-1.amazonaws.com/projetos-artes/fullsize%2f2015%2f08%2f18%2f20%2fLogo-157760_9112_205452310_775975783.jpg")
                .kindOfFood("Lanches")
                .phone("1126395732")
                .address("Rua 1 de Maio, 79")
                .menu(menuLanches)
                .build(), Place.builder()
                .id(5)
                .name("Pizzaria Me Gusta")
                .image("https://s3-sa-east-1.amazonaws.com/projetos-artes/fullsize%2f2012%2f05%2f09%2f13%2fWDL-Logo-14689_462_043508471_1478259247.jpg")
                .kindOfFood("Pizzas")
                .phone("11965789087")
                .address("Avenida Nordestina, 4000")
                .menu(pizzaMenu)
                .build(), Place.builder()
                .id(6)
                .name("Pizzaria Lucca")
                .image("https://s3-sa-east-1.amazonaws.com/projetos-artes/fullsize%2f2015%2f09%2f09%2f19%2fLogo-45316_9112_194831990_1070139805.jpg")
                .kindOfFood("Pizzas")
                .phone("11989763245")
                .address("Estrada Itaquera Guaianases, 1000")
                .menu(pizzaMenu)
                .build(), Place.builder()
                .id(7)
                .name("Sushidaki")
                .image("http://www.leaodesign.com/images/portfolio/criacao-de-logotipos/5-single.png")
                .kindOfFood("Comida Japonesa")
                .phone("1121323456")
                .address("Avenida Radial Leste, 5000")
                .menu(menuComidaJaponesa)
                .build(), Place.builder()
                .id(8)
                .name("Mr.Lanches")
                .image("https://seeklogo.com/images/M/mr-lanches-logo-6A68133B3C-seeklogo.com.jpg")
                .kindOfFood("Lanches")
                .phone("11999895930")
                .address("Rua Manuel Inácio, 30")
                .menu(menuLanches)
                .build(), Place.builder()
                .id(9)
                .name("Salgado Mania")
                .image("http://www.salgadomania.com/Imagens/logomarca.png")
                .kindOfFood("Salgados")
                .phone("1123145678")
                .address("Rua Águas Férreas, 20")
                .menu(menuSalgados)
                .build(), Place.builder()
                .id(10)
                .name("Casa Di Salgados")
                .image("http://www.casadisalgados.com.br/wp-content/uploads/2011/12/logo_home.png")
                .kindOfFood("Salgados")
                .phone("11990879054")
                .address("Rua Francisco Bucarelli, 290")
                .menu(menuSalgados)
                .build());
    }
}
